#remote_theme: artemsheludko/flexible-jekyll
title: Big Backyard Silent Auction
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bby-fundraiser.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Big Backyard Nursery School Fundraiser # add your name
author-img: david-freeman.jpg # add your photo
about-author: If you cannot make it to the event, please text your big to the number below. Please include your name, item name, and your big (in dollars). # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
